package com.example.carcatalog.entity;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

/**
 * Base class for all entities.
 * <p>
 *     The annotations are:
 *     <ul>
 *         <li>{@link MappedSuperclass} - the class is not an entity, but it is the base class for all entities</li>
 *         <li>{@link Id} - the field is the primary key</li>
 *         <li>{@link GeneratedValue} - the value is generated by the database</li>
 *    </ul>
 *    The fields are:
 *    <ul>
 *        <li>{@link UUID} id - the primary key</li>
 *    </ul>
 */
@MappedSuperclass
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public abstract class BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
}
